---
name: Check, build and run

run-name: Check, build and run triggered by @${{ github.actor }}

on:
  push:
    branches: ["main"]

env:
  APP_NAME: ${{ github.event.repository.name }}
  WORK_DIR: ${{ github.workspace }}

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest

    # needs: run-lint
    steps:
      - name: Setup Env
        run: |
          echo ::set-env name=APP_NAME::${{ env.APP_NAME }}
          echo ::set-env name=WORK_DIR::${{ env.WORK_DIR }}
          echo ::set-env name=SRC_DIR::${{ env.WORK_DIR }}/${{ env.APP_NAME }}
          echo ::set-env name=BUILD_DIR::${{ env.WORK_DIR }}/BUILD
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check & Prepare
        run: |
          ls -lah
          cd $WORK_DIR
          mkdir -p $BUILD_DIR
          ls -lah
          find . -name CMakeLists.txt
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          host: 'linux'
          target: 'desktop'
          install-deps: 'true'
          cache: 'false'
          # setup-python: 'true'
          #tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'

      - name: Configure, Build (and Test?) the Project
        uses: threeal/cmake-action@v1.3.0

        with:
          run-build: true
          run-test: false # no tests yet
          source-dir: $SRC_DIR
          build-dir: $BUILD_DIR
          generator: Ninja
          # c-compiler: clang
          # cxx-compiler: clang++
      
      - name: Check build result
        run: |
          cd $BUILD_DIR
          ls -lah
          echo 'Running application...'
          ./$APP_NAME
          echo 'Application quit. All good.'
