---
name: Check, build and run

run-name: Check, build and run triggered by @${{ github.actor }}

on:
  push:
    branches: ["main"]

env:
  APP_NAME: ${{ github.event.repository.name }}
  WORK_DIR: ${{ github.workspace }}

jobs:
  build-project:
    name: Build Project
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os}} # ubuntu-latest

    # needs: run-lint
    steps:
      - name: Setup Env
        run: |
          echo "APP_NAME=${{ env.APP_NAME }}" >> "$GITHUB_ENV"
          echo "WORK_DIR=${{ env.WORK_DIR }}" >> "$GITHUB_ENV"
          echo "SRC_DIR=$WORK_DIR/$APP_NAME" >> "$GITHUB_ENV"
          echo "BUILD_DIR=$WORK_DIR/BUILD" >> "$GITHUB_ENV"
      
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Check & Prepare
      #   run: |
      #     ls -lah
      #     cd ${{ env.WORK_DIR }}
      #     mkdir -p ${{ env.BUILD_DIR }}
      #     ls -lah
      #     find . -name CMakeLists.txt
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          host: ${{ runner.os }} # 'linux'
          target: 'desktop'
          install-deps: 'true'
          cache: 'false'

      - name: Configure the Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          run-test: false
          source-dir: ${{ env.SRC_DIR }}
          build-dir: ${{ env.BUILD_DIR }} 
      
      - name: Check build result
        run: |
          cd ${{ env.BUILD_DIR }}
          if [ "$RUNNER_OS" == "Windows" ]; then
            REM "Running the application"
            start ${{ env.APP_NAME }}
            echo "Application quit. All good."
          else
            echo 'Running application...'
            ./${{ env.APP_NAME }}
            echo 'Application quit. All good.'
          fi
          
