---
name: Check, build and run

run-name: Check, build and run triggered by @${{ github.actor }}

on:
  push:
    branches: ["main"]

env:
  APP_NAME: ${{ github.event.repository.name }}
  WORK_DIR: ${{ github.workspace }}

jobs:
  build-project:
    name: Build Project
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }} # ubuntu-latest

    # needs: run-lint
    steps:
      - name: Setup Env on Linux or macOS
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          echo "APP_NAME=${{ env.APP_NAME }}" >> "$GITHUB_ENV"
          echo "WORK_DIR=${{ env.WORK_DIR }}" >> "$GITHUB_ENV"
          echo "SRC_DIR=$WORK_DIR/$APP_NAME" >> "$GITHUB_ENV"
          echo "BUILD_DIR=$WORK_DIR/BUILD" >> "$GITHUB_ENV"
      
      - name: Setup Env on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          "APP_NAME=${{ env.APP_NAME }}" | Out-File -FilePath $env:GITHUB_ENV -Append
          "WORK_DIR=${{ env.WORK_DIR }}" | Out-File -FilePath $env:GITHUB_ENV -Append
          "SRC_DIR=${{ env.WORK_DIR }}/${{ env.APP_NAME }}" | Out-File -FilePath $env:GITHUB_ENV -Append
          "BUILD_DIR=${{ env.WORK_DIR }}/BUILD" | Out-File -FilePath $env:GITHUB_ENV -Append
      
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          host: ${{ (runner.os == 'Linux' && 'linux') || (runner.os == 'macOS' && 'mac' || 'windows') }}

      - name: Configure and Build the Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          run-test: false
          source-dir: ${{ env.SRC_DIR }}
          build-dir: ${{ env.BUILD_DIR }} 
      
      - name: Check build result on Linux or macOS
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          cd ${{ env.BUILD_DIR }}
          echo 'Running the application...'
          ./${{ env.APP_NAME }}
          echo 'Application quit. All good.'

      - name: Check build result on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd ${{ env.BUILD_DIR }}
          Write-Output "Running the application..."
          Start-Process -FilePath "${{ env.APP_NAME }}.exe" -Wait
          Write-Output "Application quit. All good."


          
