---
name: Check, build and run

run-name: Check, build and run triggered by @${{ github.actor }}

on:
  push:
    branches: ["main"]

env:
  APP_NAME: ${{ github.event.repository.name }}
  WORK_DIR: ${{ github.workspace }}

jobs:
  build-project:
    name: Build Project
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }} # ubuntu-latest

    # needs: run-lint
    steps:
      - name: Setup Env for Linux or macOS
        if: ${{ matrix.os != 'windows' }}
        run: |
          echo "APP_NAME=${{ env.APP_NAME }}" >> "$GITHUB_ENV"
          echo "WORK_DIR=${{ env.WORK_DIR }}" >> "$GITHUB_ENV"
          echo "SRC_DIR=$WORK_DIR/$APP_NAME" >> "$GITHUB_ENV"
          echo "BUILD_DIR=$WORK_DIR/BUILD" >> "$GITHUB_ENV"
      
      - name: Setup Env for Windows
        if: ${{ matrix.os == 'windows' }}
        run: |
          "APP_NAME=${{ env.APP_NAME }}" | Out-File -FilePath $env:GITHUB_ENV -Append
          "WORK_DIR=${{ env.WORK_DIR }}" | Out-File -FilePath $env:GITHUB_ENV -Append
          "SRC_DIR=${{ env.WORK_DIR }}/${{ env.APP_NAME }}" | Out-File -FilePath $env:GITHUB_ENV -Append
          "BUILD_DIR=${{ env.WORK_DIR }}/BUILD" | Out-File -FilePath $env:GITHUB_ENV -Append
      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          host: ${{ (runner.os == 'Linux' && 'linux') || (runner.os == 'macOS' && 'mac' || 'windows') }}

      - name: Configure the Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          run-test: false
          source-dir: ${{ env.SRC_DIR }}
          build-dir: ${{ env.BUILD_DIR }} 
      
      - name: Check build result
        run: |
          cd ${{ env.BUILD_DIR }}
          if [ "$RUNNER_OS" == "Windows" ]; then
            REM "Running the application"
            ${{ env.APP_NAME }}
            echo "Application quit. All good."
          else
            echo 'Running application...'
            ./${{ env.APP_NAME }}
            echo 'Application quit. All good.'
          fi
          
