---
# This workflow executes the following linters:
#    bash, clang-format, github-actions, gitleaks, md, py
# on the whole codebase in the "full-check" branch.
name: Lint Code Base

on:
  push:
    branches: ["full-check"]

env:
  # Only for .clang-format in the root folder of the project:
  LINTER_RULES_PATH: $GITHUB_WORKSPACE

jobs:
  run-full-project-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list
          # of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true # to check touched files only
          VALIDATE_BASH: true
          VALIDATE_CLANG_FORMAT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PYTHON: true
          # VALIDATE_NATURAL_LANGUAGE: true # do it someday...
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
